name: Test Build and Apply

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  BuildAndApply:
    name: Build and Apply Test
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hello World!!!"
